apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: adb-config
            secret:
              secretName: {{ .Values.adbSecret.name }}
          containers:
          - name: frameo-injector
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            command:
            - /app/dist/index.js
            - replicate
            volumeMounts:
            - name: adb-config
              readOnly: true
              mountPath: "/root/.android/adbkey"
              subPath: {{ .Values.adbSecret.privateKeySubPath }}
            - name: adb-config
              readOnly: true
              mountPath: "/root/.android/adbkey.pub"
              subPath: {{ .Values.adbSecret.publicKeySubPath }}
            env:
              - name: GOOGLE_OAUTH2_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name | required ".Values.secret.name is required." }}
                    key: GOOGLE_OAUTH2_CLIENT_ID
              - name: GOOGLE_OAUTH2_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name }}
                    key: GOOGLE_OAUTH2_CLIENT_SECRET
              - name: GOOGLE_OAUTH2_CLIENT_REDIRECT_URI
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name }}
                    key: GOOGLE_OAUTH2_CLIENT_REDIRECT_URI
              - name: GOOGLE_OAUTH2_ACCESS_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name }}
                    key: GOOGLE_OAUTH2_ACCESS_TOKEN
              - name: GOOGLE_OAUTH2_REFRESH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name }}
                    key: GOOGLE_OAUTH2_REFRESH_TOKEN
              - name: GOOGLE_OAUTH2_TOKEN_EXPIRY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name }}
                    key: GOOGLE_OAUTH2_TOKEN_EXPIRY
              - name: GOOGLE_DRIVE_FOLDER_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name }}
                    key: GOOGLE_DRIVE_FOLDER_ID
              - name: REMOTE_DEVICE_HOST
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name }}
                    key: REMOTE_DEVICE_HOST
              - name: REMOTE_DEVICE_ADBPORT
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name }}
                    key: REMOTE_DEVICE_ADBPORT
              - name: REMOTE_DEVICE_PATH
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secret.name }}
                    key: REMOTE_DEVICE_PATH
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 512Mi
          restartPolicy: Never
