name: Publish Docker Image
on:
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Extract tag name
        id: releaseTag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/refs\/tags\//, '');
      - name: 'Build Inventory Image'
        run: |
          docker build --file Dockerfile . -t "ghcr.io/codingwithkansas/frameo-injector:${{ steps.releaseTag.outputs.result }}"
          docker push "ghcr.io/codingwithkansas/frameo-injector:${{ steps.releaseTag.outputs.result }}"
